# Default values for elasticsearch2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

storage:
  accessModes: [ "ReadWriteOnce" ]
  capacity: 20Gi
  storageClass: gc2

image:
  repository: elasticsearch
  tag: 6.8.6
  pullPolicy: IfNotPresent

dashboard:
  enabled: false

# Whether we should create an ingress rule for the elastichq dashboard
ingress:
  enabled: false
  host: "elasticsearch.localhost"

# Drop-in values for elasticsearch.yml config file:
elasticsearch:
  config:
    cluster.name: "sanity-es"
    #discovery.zen.minimum_master_nodes: 2 # ${NODE_QUORUM}


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 750m
   memory: 1024Mi
  requests:
   cpu: 250m
   memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}